/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    HeaderCon: typeof import('./src/components/Header/HeaderCon.vue')['default']
    Page: typeof import('./src/components/Pages/Page.vue')['default']
    ReservationCourses: typeof import('./src/components/List/ReservationCourses.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarCon: typeof import('./src/components/Sidebar/sidebarCon.vue')['default']
    Teachers: typeof import('./src/components/List/Teachers.vue')['default']
    TodayCourses: typeof import('./src/components/List/TodayCourses.vue')['default']
  }
}
